### ISSUE TITLE
Breaking changes have been made in a patch version

### ISSUE THREAD

**Issue by jackghicks** [TooTallNate/node-get-uri#13]
Hi just wanted to let you know that going into version 2.0.3 you've updated major versions of your dependencies without incrementing your own major version number.  

This means that those maintaining legacy code on node <=5 will probably hit issues with block scoped variables amongst other things the next time they update any modules that depend, anywhere in the dependency chain, on this module.

**Comment by conorstrejcek** [comment]
I can confirm that this is affecting us in one of our projects -- we use the `mailgun-js` npm package, and `get-uri` appears in its dependency tree, which has caused our application to stop building. I was able to fix it by manually adjusting the version of one of its parents (pac-proxy-agent@1.0.0), which pulled in an older version of the package.

**Comment by ezekg** [comment]
Can confirm. Broke support for Node 4.8.4.

**Comment by ziedmahdi** [comment]
you can fix this problem by settings the get-uri version:
` npm i --save get-uri@2.0.2`

**Comment by jackghicks** [comment]
@ziedmahdi I'm pretty sure that only works if it is your own module that is including get-uri, right?  If you are using a 3rd party module which includes get-uri with any form of wildcard, all this will do is include a second copy of get-uri at 2.0.2 for your own usage, whilst still pulling the latest in the 3rd party module and breaking the support for Node<4 ?

**Comment by ziedmahdi** [comment]
@jackghicks I'm not an expert on how node dependencies manager works, but I don't own any npm module, I use `mailgun-js:@0.13.1` in a MeteorJs project.

**Comment by ezekg** [comment]
FWIW, you can use a resolution in your `package.json` to override dependency versions:

```js
"resolutions": {
  // Override a specific dependency (the foo-bar module)
  "foo-bar/get-uri": "2.0.2",
  // Overall all dependencies
  "get-uri": "2.0.2"
}
```

But in my case, I actually was able to simply override the `debug` version:

```js
"resolutions": {
  "get-uri/debug": "^3.2.5"
}
```

Hope that helps somebody.

**Comment by jackghicks** [comment]
@ezekg Interesting!  Is that a yarn feature, or does it work directly in npm now?  I've seen this module https://www.npmjs.com/package/npm-force-resolutions  perhaps you are using that?

I remember seeing the breaking change in the patch version on the `debug` module - the developer corrected that mistake though, and moved the breaking change to a major version update - so get-uri remains broken, as it is still now using the latest major version of `debug`.

Thanks all for your workarounds so far - of course the real solution is for @TooTallNate to revert the change, and issue a new major version release with the breaking changes instead, just as the `debug` developer did.  Any chance you could take a look at that? 😃

**Comment by ezekg** [comment]
It's a Yarn feature.

**Comment by miguelBinpar** [comment]
Same problem here. Are there any news? Or is there any workaround without migrating to yarn?

We can't use yarn, so we can't use resolutions. And we are facing this problem because we are using mailgun-js package. This package is a forth level dependency for mailgun-js, so as long as we can't force reference with resolutions only solution would be to fork all parent packages until we can change the direct reference to 2.0.2. Is there any other option?

**Comment by jackghicks** [comment]
@miguelBinpar we have a private npm server and so were able to publish our own override version of this package to fix the issue.  If you don't have that (which is perfectly normal!) and you can't use yarn, the only other thing I can think of is for you to try https://www.npmjs.com/package/npm-force-resolutions

Good luck!

In the meantime, we await the simplest solution - for @TooTallNate to resolve this issue with an unpublish, and publish with the correct version numbering.

**Comment by miguelBinpar** [comment]
@jackghicks thanks a lot for your answer!

We don't have a private npm server (I wish we had one) and the problem with resolutions package is that we can't make it work with our deploy system (based on Mup).
We finally just decided to add a patch to our deploy system. It's kind of ugly, but it works. After deploy we install version 2.0.2 of get-uri globally and delete version 2.0.3 from mailgun-js node_modules folder, so right version is used...

I hope @TooTallNate can give us a hand so we don't need these workarounds...

**Comment by TooTallNate** [comment]
Sorry about the delay. Please use [v2.0.4](https://github.com/TooTallNate/node-get-uri/releases/tag/2.0.4) if you're still using Node 4.x.
