### ISSUE TITLE
Dependency on 'ftp' causes [DEP0005] DeprecationWarning: Buffer()

### ISSUE THREAD

**Issue by baerrach** [TooTallNate/node-get-uri#18]
See https://github.com/mscdex/node-ftp/issues/255

**Comment by samjegal** [comment]
I've get uri 'https://registry.npmjs.org/get-uri/-/get-uri-2.0.4.tgz'. package.json include in github data-uri-to-buffer: "3", but downloaded file had below version.

```
  "dependencies": {
    "data-uri-to-buffer": "1",
    "ftp": "~0.3.10",
    "debug": "2",
    "extend": "~3.0.2",
    "file-uri-to-path": "1",
    "readable-stream": "2"
  }
```
