### ISSUE TITLE
The request of a dependency is an expression

### ISSUE THREAD

**Issue by lededje** [TooTallNate/node-get-uri#6]
Using mailgun-js which uses this package which breaks a fairly fundemental rule; Don't use expressions as dependencies.

It causes tools like Webpack to throw up, trying to include every last file in your package.

https://github.com/TooTallNate/node-get-uri/blob/master/index.js#L29

I've not looked into why this is used, but please consider changing it.

**Comment by TooTallNate** [comment]
Ya, probably too magical. I've deprecated the call in 128eac72f69ef4d3be1f6980e94f8e1bc25fc29e for v1.1.1, and removed it for good in v2.0.0 in ac3f1a1bae3aad038c4b5a08815363f84ae235d4.

_Side note:_ I'm not so sure this module would work properly on the client-side... Not sure why you're tryin to run it through Webpack to begin with.

**Comment by lededje** [comment]
Running compiled minified files when using Lambda
