### ISSUE TITLE
S3 protocol handler

### ISSUE THREAD

**Issue by rmm5t** [TooTallNate/node-get-uri#8]
Would you be interested in a pull-request for an S3 protocol handler that accepts URLs of the form `s3://bucket/path/to/key`?  I wrote one for an application we're building. It works well, but I haven't yet implemented a `cache` option.  Because the `aws-sdk` node package is somewhat large, I'd suggest only conditionally importing the s3 protocol if the `aws-sdk` is available.

**Comment by TooTallNate** [comment]
Do we really need the entire `aws-sdk` for this single task of GETing a file from S3 though? Maybe we could implement the required logic manually.

**Comment by rmm5t** [comment]
My thought was to use `require.resolve("aws-sdk")` to see if the aws-sdk is available and only require the s3 module if so.

**Comment by rmm5t** [comment]
> Ideally s3:// would just be a simple layer on top of the https handler, so that we get caching and stuff for free.

That's an interesting idea. I'd want it to still work for private buckets, so it'd have to automatically convert to using signed URLs based on AWS environment variables or passed key/secret parameters, but aws-sdk also allows you to use credential files for auth (which is much more aws-sdk specific).

**Comment by TooTallNate** [comment]
Isn't the URL format simply `https://${region}.amazonaws.com/${bucket}/${key}`?

Regarding private buckets / signed URLs: how does the `s3://` URL convey that information?

**Comment by TooTallNate** [comment]
Possibly related https://github.com/aws/aws-cli/issues/451.

The `s3` CLI tool supports these URLs it looks like?

**Comment by rmm5t** [comment]
> Isn't the URL format simply https://${region}.amazonaws.com/${bucket}/${key}?

Yes, but not for signed URLs. It requires a key, expiry timestamp, and a signature based on the secret and timestamp.

> how does the s3:// URL convey that information?

It doesn't. The protocol managed by the `aws-sdk` (`s3.getObject(...)`) handles the credential headers.

> The s3 CLI tool supports these URLs it looks like?

I don't think that CLI discussion is relevant to this discussion, but I might be misunderstanding you here.

Overall, I think the real problem to avoiding the `aws-sdk` package is determining where AWS credentials should be pulled from. When considering serverless environments on AWS (or any AWS environment or that matter), IAM handles all the credentials, and you don't typically deal with the raw access keys or secrets directly. There are just a lot of options that I don't think we'd want to deal with in this package. 

* AWS credentials can be handled by environment variables
* AWS credentials can be handled by a global aws-sdk configuration
* AWS credentials can be handled by a global aws-sdk configuration, but one that's specific to the S3 module alone.
* AWS credentials might be handled by a credentials file that references a particular AWS_PROFILE within that file.
* AWS credentials can even be assigned via a role to just a particular EC2 instance, and any access to S3 (via the aws-sdk or aws-cli) from any user on that EC2 instance is auto-magically granted access.

**Comment by TooTallNate** [comment]
So this would probably be better implemented as a plugin style module: `get-uri-s3`

 Take a look at https://github.com/TooTallNate/node-get-uri-tftp for an example. This way, you would make `get-uri` a peer dependency of `get-uri-s3` module.

Does that sound good to you?

**Comment by TooTallNate** [comment]
Also I'd be happy to list the plugin in `get-uri`'s README if/when you create it.

**Comment by rmm5t** [comment]
> So this would probably be better implemented as a plugin style module: get-uri-s3

That's perfectly reasonable, and a response I somewhat anticipated, but I thought I'd check with you first to see if you were interested in first dibs.
